config/routes.rb
# == Route Map
#
#                    Prefix Verb   URI Pattern                                                                              Controller#Action
#                   tarefas GET    /tarefas(.:format)                                                                       tarefas#index
#                           POST   /tarefas(.:format)                                                                       tarefas#create
#                new_tarefa GET    /tarefas/new(.:format)                                                                   tarefas#new
#               edit_tarefa GET    /tarefas/:id/edit(.:format)                                                              tarefas#edit
#                    tarefa GET    /tarefas/:id(.:format)                                                                   tarefas#show
#                           PATCH  /tarefas/:id(.:format)                                                                   tarefas#update
#                           PUT    /tarefas/:id(.:format)                                                                   tarefas#update
#                           DELETE /tarefas/:id(.:format)                                                                   tarefas#destroy
#                      root GET    /                                                                                        pages#home
#          new_user_session GET    /users/sign_in(.:format)                                                                 devise/sessions#new
#              user_session POST   /users/sign_in(.:format)                                                                 devise/sessions#create
#      destroy_user_session DELETE /users/sign_out(.:format)                                                                devise/sessions#destroy
#         new_user_password GET    /users/password/new(.:format)                                                            devise/passwords#new
#        edit_user_password GET    /users/password/edit(.:format)                                                           devise/passwords#edit
#             user_password PATCH  /users/password(.:format)                                                                devise/passwords#update
#                           PUT    /users/password(.:format)                                                                devise/passwords#update
#                           POST   /users/password(.:format)                                                                devise/passwords#create
#  cancel_user_registration GET    /users/cancel(.:format)                                                                  devise/registrations#cancel
#     new_user_registration GET    /users/sign_up(.:format)                                                                 devise/registrations#new
#    edit_user_registration GET    /users/edit(.:format)                                                                    devise/registrations#edit
#         user_registration PATCH  /users(.:format)                                                                         devise/registrations#update
#                           PUT    /users(.:format)                                                                         devise/registrations#update
#                           DELETE /users(.:format)                                                                         devise/registrations#destroy
#                           POST   /users(.:format)                                                                         devise/registrations#create
#        rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#        rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  resources :tarefas
  root to: 'pages#home'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tarefa.rb
# == Schema Information
#
# Table name: tarefas
#
#  id         :bigint           not null, primary key
#  title      :string
#  body       :text
#  date       :date
#  user_id    :bigint
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# class DatetimeValidator < ActiveModel::Validator
#   def validate(record)
#       # if record.date == nil
#       #     record.errors[:base] << "Time and Date must be defined."
#       if record.date < Date.current()
#           record.errors[:base] << "A Data Não Pode Ser Anterior a Hoje!"
#       end
#   end
# end

class Tarefa < ApplicationRecord
  belongs_to :user
  validate :invalid_date
  validates :title, :body, presence: true
  validates_length_of :title, minimum: 5, too_short: 'O Título Deve Conter Mais que 5 Caracteres!'

  private

    def invalid_date
      if date && date < Date.today
        errors.add(:date, "Data tem que ser a partir de hoje!")
      end
    end

  # validates_with DatetimeValidator

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  def username
    return self.email.split('@')[0].capitalize
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/tarefas_controller.rb
class TarefasController < ApplicationController
  before_action :set_tarefa, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]
  # GET /tarefas
  # GET /tarefas.json
  def index
    @tarefas = Tarefa.all
  end

  # GET /tarefas/1
  # GET /tarefas/1.json
  def show
  end

  # GET /tarefas/new
  def new
    @tarefa = Tarefa.new
  end

  # GET /tarefas/1/edit
  def edit
  end

  # POST /tarefas
  # POST /tarefas.json
  def create
    @tarefa = Tarefa.new(tarefa_params)
    @tarefa.user = current_user
    respond_to do |format|
      if @tarefa.save
        format.html { redirect_to @tarefa, notice: 'Tarefa was successfully created.' }
        format.json { render :show, status: :created, location: @tarefa }
      else
        format.html { render :new }
        format.json { render json: @tarefa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tarefas/1
  # PATCH/PUT /tarefas/1.json
  def update
    respond_to do |format|
      if @tarefa.update(tarefa_params)
        format.html { redirect_to @tarefa, notice: 'Tarefa was successfully updated.' }
        format.json { render :show, status: :ok, location: @tarefa }
      else
        format.html { render :edit }
        format.json { render json: @tarefa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tarefas/1
  # DELETE /tarefas/1.json
  def destroy
    @tarefa.destroy
    respond_to do |format|
      format.html { redirect_to tarefas_url, notice: 'Tarefa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tarefa
      @tarefa = Tarefa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tarefa_params
      params.require(:tarefa).permit(:title, :body, :date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tarefas_helper.rb
module TarefasHelper
end

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/_footer.html.erb
<footer class="card-panel light-blue">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="white-text">Quem eu sou?</h5>
          <p class="grey-text text-lighten-4">Sou extremamente esforçado, pois desejo de verdade me tornar um programador experiente. Tenho o desejo
            de mudar de país com minha família. Então estou estudando Inglês e Espanhol.
          </p>


        </div>
        <!-- <div class="col l3 s12">
          <h5 class="white-text">Settings</h5>
          <ul>
            <li><a class="white-text" href="#!">Link 1</a></li>
            <li><a class="white-text" href="#!">Link 2</a></li>
            <li><a class="white-text" href="#!">Link 3</a></li>
            <li><a class="white-text" href="#!">Link 4</a></li>
          </ul>
        </div> -->
        <div class="col l4 s12">
          <h5 class="white-text">Contatos / Contacts</h5>
            <a class="white-text" href="https://www.linkedin.com/in/diego-araujo-56897a129/"><i class="fab fa-linkedin fa-4x"></i></a>
            <a class="white-text" href="https://github.com/diegoshakan"> <i class="fab fa-github fa-4x"></i></a>
            <a class="white-text" href="https://www.instagram.com/diegoshakan/"> <i class="fab fa-instagram fa-4x"></i></a>
            <a class="white-text" href="https://www.facebook.com/diego.araujo.900?ref=bookmarks"> <i class="fab fa-facebook-square fa-4x"></i></a>
          <!-- <ul>
            <li><i class="fab fa-linkedin fa-2x"></i> <a class="white-text" href="https://www.linkedin.com/in/diego-araujo-56897a129/">Linked In</a></li>
            <li><i class="fab fa-github fa-2x"></i> <a class="white-text" href="https://github.com/diegoshakan">Github</a></li>
            <li><i class="fab fa-instagram fa-2x"></i> <a class="white-text" href="https://www.instagram.com/diegoshakan/">Instagram</a></li>
            <li><a class="white-text" href="#!">Link 4</a></li>
          </ul> -->
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container center">
      <!-- Made with <a class="white-text text-lighten-3" href="http://materializecss.com">Materialize</a> -->
      </div>
    </div>
  </footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-primary">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <%= link_to 'Registre-se', new_user_registration_path, class:"nav-link" %>
      </li>
      <% if user_signed_in? %>
      <li class="nav-item">
      <%= link_to 'Ver Tarefas', tarefas_path, class:"nav-link" %>
      <li class="nav-item">
      <li class="nav-item">
      <%= link_to 'Sair', destroy_user_session_path, method: :delete, class:"nav-link" %>  
      <li class="nav-item">
      
        <p class="nav-link" style="position: relative; left: 100%"><%= current_user.username %></p>
      </li>
      </li>
      <% else %>      
      <%= link_to 'Entrar', new_user_session_path , class:"nav-link" %><br>
      <% end %>
      
    </ul>
  </div>
</nav>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar'%>
    <%= render 'layouts/alerts' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<center> <h1>To Do - Sua Lista de Tarefas</h1> </center>

<center> <div class="col-md-6" >
    <p align="justify">
        Venha hoje aproveitar este novo sistema desenvolvido especialmente para você que gosta de manter
        suas tarefas sob controle, e para você também que costuma esquecer dos seus compromissos.
        Registre-se hoje, totalmente grátis, e usufrua de todo o nosso conteúdo.
    </p>
     <figure>
  <img src="https://tudosobrehospedagemdesites.com.br/site/wp-content/uploads/2016/03/facil-de-lembrar-728x364.png" alt="The Pulpit Rock" width="304" height="228">
</figure> 
</div>
</center>


<!--
<%= link_to 'Ver Tarefas', tarefas_path %><br>
<% if current_user %>
    <%= link_to 'Sair', destroy_user_session_path, method: :delete %>
<% else %>
    <%= link_to 'Entrar', new_user_session_path %><br>
    <%= link_to 'Registre-se', new_user_registration_path %>
<% end %>
-->

app/views/tarefas/_form.html.erb
<%= form_with(model: tarefa, local: true) do |form| %>
  <% if tarefa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tarefa.errors.count, "error") %> prohibited this tarefa from being saved:</h2>

      <ul>
      <% tarefa.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tarefas/edit.html.erb
<h1>Editing Tarefa</h1>

<%= render 'form', tarefa: @tarefa %>

<%= link_to 'Show', @tarefa %> |
<%= link_to 'Back', tarefas_path %>

app/views/tarefas/index.html.erb
<p id="notice"><%= notice %></p>


<center> 
<h1>Minhas Tarefas</h1>

<div class="col-md-8" >
<table>
  <thead>
    <tr>
      <th>Título</th>
      <th>Descrição</th>
      <th>Data</th>
      <th>Usuário</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    
    <% @tarefas.each do |tarefa| %>
      <% if tarefa.user == current_user%>
        <tr>
          <td><%= tarefa.title %></td>
          <td><%= tarefa.body.truncate_words(3) %></td>
          <td><%= tarefa.date %></td>
          <td><%= tarefa.user.username %></td>
          <td><%= link_to 'Ler', tarefa %></td>
          <td><%= link_to 'Editar', edit_tarefa_path(tarefa) %></td>
          <td><%= link_to 'Deletar', tarefa, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
</div> 
</center>

<br>
<div class="col-md-4">
      <p>
        <%= link_to 'Adicione Nova Tarefa', new_tarefa_path %><br>
      </p>
</div>

app/views/tarefas/new.html.erb
<h1>New Tarefa</h1>

<%= render 'form', tarefa: @tarefa %>

<%= link_to 'Back', tarefas_path %>

app/views/tarefas/show.html.erb
<p>
  <strong>Título:</strong>
  <%= @tarefa.title %>
</p>

<p>
  <strong>Descrição:</strong>
  <%= @tarefa.body %>
</p>

<p>
  <strong>Data:</strong>
  <%= @tarefa.date %>
</p>

<p>
  <strong>Usuário:</strong>
  <%= @tarefa.user.username %>
</p>

<%= link_to 'Editar', edit_tarefa_path(@tarefa) %> |
<%= link_to 'Voltar', tarefas_path %>